[project]
name = "hermes_artefact_parser"
version = "0.1.0"
description = "Hermes artefact parser"
authors = [
    { name = "Brocoli Data", email = "contact.brocoli@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "hermes",
    "jsonschema>=4.23.0",
    "typer>=0.15.3",
    "click<8.2.0",
    "omegaconf>=2.3.0"
]

[tool.uv]
package = true

[project.scripts]
hermes-artefact-parser = "artefact_parser.cli:app"

[tool.uv.sources]
hermes = { path = "/hermes", editable = true}