[project]
name = "hermes"
version = "0.4.0"
description = "Lightweight Python data ingestion framework"
readme = "README.md"
authors = [
    { name = "Brocoli Data", email = "contact.brocoli@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "omegaconf>=2.3.0",
]
[tool.uv.sources]
custom_source = { path = "./plugins/sources/custom", editable = true}
athena_iceberg_destination = { path = "./plugins/destinations/athena_iceberg", editable = true }
s3_destination = { path = "./plugins/destinations/s3", editable = true }
generic_object_storage_destination = { path = "./plugins/destinations/generic_object_storage", editable = true}
hermes_artefact_parser = { path = "./plugins/utils/hermes_artefact_parser", editable = true}

[project.optional-dependencies]
custom_source = [
    "custom_source"
]

athena_iceberg_destination = [
    "athena_iceberg_destination"
]

s3_destination = [
    "generic_object_storage_destination",
    "s3_destination"
]

ingestion_core = [
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
    "requests>=2.32.3",
]

artefact_parser = [
    "hermes_artefact_parser"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "moto>=5.1.1",
    "pytest>=8.3.4",
    
]
athena_iceberg_destination_dev = [
    "awswrangler>=3.10.1",
]
