name: Build and Publish Lambda Layer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install zip

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies
        working-directory: src
        run: >
          uv sync 
          --all-extras 
          --all-groups

      - name: Export Requirements
        working-directory: src
        run: >
          uv export 
          --all-extras 
          --no-extra ingestion_core
          --no-dev 
          --no-editable
          --format requirements-txt 
          -o lambda_layer_requirements.txt

      - name: Create Lambda Layer directory
        working-directory: src
        run: mkdir -p lambda_layer/python

      - name: Install Dependencies for Layer
        working-directory: src
        run: >
          uv pip install 
          --target=lambda_layer/python 
          -r lambda_layer_requirements.txt

      - name: Zip Lambda Layer
        working-directory: src/lambda_layer
        run: zip -q -r lambda_layer.zip python

      - name: Upload Lambda Layer as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hermes-zip-lambda-layer
          path: src/lambda_layer/lambda_layer.zip
          overwrite: true
          if-no-files-found: error
          compression-level: 0