name: 'CI Pipeline'

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    paths:
      - 'src/**'

jobs:

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Python'
        uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: 'Install dependencies'
        id: install_dependencies
        working-directory: ${{ github.workspace }}/src
        run: |
          uv sync --all-extras
      - name: 'Run tests'
        id: run_tests
        if: steps.install_dependencies.outcome == 'success'
        working-directory: ${{ github.workspace }}/src/tests
        env:
          HERMES_CONFIG_FOLDER: "${{ github.workspace }}/src/tests/assets/config"
          HERMES_ARTIFACTS_FOLDER: "${{ github.workspace }}/src/tests/assets/artifacts"
          HERMES_CUSTOM_CONNECTORS_FOLDER: "${{ github.workspace }}/src/tests/assets/custom"
        run: |
          uv run pytest --junit-xml pytest_.xml
      - name: 'Publish tests results'
        if: success() || failure()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "${{ github.workspace }}/src/tests/pytest_.xml"